title = "RbxBehaviorTree"
gitRepoUrl = "https://github.com/Fangous/RbxBehaviorTree"
gitSourceBranch = "main"
projectName = "RbxBehaviorTree"
url = "https://fangous.github.io"
tagline = "A simple behavior tree implementation for Roblox."
autoSectionPath = "src"

[docusaurus]
url = "https://fangous.github.io"
baseUrl = "/RbxBehaviorTree"

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Visualizer Plugin"
description = "Our plugin allows for quick and easy debugging of larger behavior trees."

[[home.features]]
title = "Rojo Friendly"
description = "All of your behavior trees are created declaratively using primitives."

[[home.features]]
title = "Composable"
description = "Nodes used by multiple behavior trees can be broken up into modules/factories for easy reuse."