[tools]
rojo = "rojo-rbx/rojo@7.4.4"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.2"
selene = "kampfkarren/selene@0.25.0"
stylua = "johnnymorganz/stylua@0.19.1"